UNAME := $(shell uname)

ifeq ($(UNAME), Linux)
	AS = as --32
	LD = ld
	#LDFLAGS = -m elf_i386 -x
	LDFLAGS = -m elf_i386
	CC = gcc
	CFLAGS = -g -m32 -fno-builtin -fno-stack-protector -fomit-frame-pointer -fstrength-reduce -Wall
	CPP = cpp -nostdinc
	AR = ar
	STRIP = strip
	OBJCOPY = objcopy
	OBJDUMP = objdump
	NM = nm
	gcc_version = $(shell ls -l 'which gcc' | tr '-' '\n' | tail -1)
endif
