obj-y := bitmap.o block_dev.o buffer.o char_dev.o exec.o fcntl.o file_dev.o \
	   file_table.o inode.o ioctl.o namei.o open.o pipe.o read_write.o \
	   stat.o super.o truncate.o

CFLAGS_file_dev.o := -O0
